<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>yolo26_seg</name>
  <version>0.0.0</version>
  <description>YOLO Segmentation Detection Node with TensorRT for ROS2</description>
  <maintainer email="rykj@example.com">RYKJ</maintainer>
  <license>Apache License 2.0</license>

  <!-- 构建工具依赖 -->
  <buildtool_depend>ament_python</buildtool_depend>
  
  <!-- ROS2核心依赖 -->
  <depend>rclpy</depend>
  
  <!-- ROS2消息类型依赖 -->
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>message_filters</depend>

  <!-- 自定义服务接口 -->
  <depend>yolo_interfaces</depend>
  
  <!-- 测试依赖 -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
